server:
  port: 8083
spring:
    application:
      name: leyou-search
    data:
      elasticsearch:
        cluster-name: zwfw
        cluster-nodes: 192.168.191.103:9300
        
    main:
      allow-bean-definition-overriding: true
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
    registry-fetch-interval-seconds: 10
  instance:
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 15
    
